In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("E:/100 Days Machine Learning/Data Sets/titanic_02.csv")
df = df.rename(columns={"number":"family_members"})

Working on "family_members"

In [3]:
df['family_members'].unique()

array(['5', '3', '6', 'A', '2', '1', '4'], dtype=object)

Method 1 : Convert 'A' (Alone) -> '0. Then convert all values to integer

In [4]:
df['family_members'] = df['family_members'].replace('A','0').astype('int32')

In [5]:
df

    Cabin            Ticket  family_members  Survived
0     NaN         A/5 21171               5         0
1     C85          PC 17599               3         1
2     NaN  STON/O2. 3101282               6         1
3    C123            113803               3         1
4     NaN            373450               0         0
..    ...               ...             ...       ...
886   NaN            211536               3         0
887   B42            112053               3         1
888   NaN        W./C. 6607               1         0
889  C148            111369               2         1
890   NaN            370376               3         0

[891 rows x 4 columns]

Working on "Cabin"

In [6]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [7]:
df['cabin_no'] = df['Cabin'].str.extract('(\d+)')   # captures only numeric part of data
df['cabin_cat'] = df['Cabin'].str[0]                # captures first letter only

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Chirag S\AppData\Local\Temp\ipykernel_7680\2177523258.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['cabin_no'] = df['Cabin'].str.extract('(\d+)')   # captures only numeric part of data

In [8]:
df

    Cabin            Ticket  family_members  Survived cabin_no cabin_cat
0     NaN         A/5 21171               5         0      NaN       NaN
1     C85          PC 17599               3         1       85         C
2     NaN  STON/O2. 3101282               6         1      NaN       NaN
3    C123            113803               3         1      123         C
4     NaN            373450               0         0      NaN       NaN
..    ...               ...             ...       ...      ...       ...
886   NaN            211536               3         0      NaN       NaN
887   B42            112053               3         1       42         B
888   NaN        W./C. 6607               1         0      NaN       NaN
889  C148            111369               2         1      148         C
890   NaN            370376               3         0      NaN       NaN

[891 rows x 6 columns]